# Generated by Django 6.0.8 on 2026-08-08 11:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[accounts.models.validate_resume]),
        ),
    ]
